version: '3.8'

services:
  backend:
    build: ./backend
    container_name: fastapi-backend
    ports:
      - "8081:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
